[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

# CKAN Web Service
[program:ckan]
command=sh /srv/app/start_ckan.sh
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/ckan.log
stderr_logfile=/var/log/ckan.err.log
user=ckan

# CKAN gRPC RPC Service
[program:ckan-rpc]
command=sh /srv/app/start_rpc.sh
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=10
stdout_logfile=/var/log/ckan-rpc.log
stderr_logfile=/var/log/ckan-rpc.err.log
user=ckan

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
